import type { Metadata } from 'next';
import React from 'react';
import '../globals.css';
import NavBar from '../_components/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-w-screen flex min-h-screen flex-col`}>
        <NavBar></NavBar>
        <div className="flex h-full w-screen flex-1 items-center justify-center bg-[#F9F9F9]">
          {children}
        </div>
      </body>
    </html>
  );
}
