import type { Metadata } from "next";
import React from "react";
import '../globals.css'
import NavBar from "../_components/navbar";
import localFont from 'next/font/local'

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LoginLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`min-h-screen min-w-screen flex flex-col`}>
                <NavBar></NavBar>
                <div className="bg-[#F9F9F9] h-full flex flex-1 justify-center items-center w-screen">
                    {children}
                </div>
            </body>
        </html>
    );
}
