import type { Metadata } from 'next';
import React from 'react';
import '../globals.css';
import NavBar from '../_components/navbar';
import { AuthProvider } from '@/context/AuthContext';
import SearchBar from './_components/searchBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className="h-screen max-h-screen overflow-hidden">
          <NavBar></NavBar>
          <SearchBar></SearchBar>
          <div className="flex w-full flex-row">
            <div className="my-5 w-1/4 border-r border-black pr-4">555</div>
            <div className="w-3/4 pl-4">{children}</div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
